# Generated by Django 2.2 on 2019-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20190405_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.png', upload_to='profile_pics'),
        ),
    ]
