# Generated by Django 2.2 on 2019-04-08 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20190408_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_buyer',
        ),
    ]
