# Generated by Django 2.2 on 2019-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_remove_profile_is_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(choices=[(True, 'Seller'), (False, 'Buyer')], default=False),
        ),
    ]
