# Generated by Django 2.2 on 2019-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Property', '0002_auto_20190408_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_city',
            field=models.CharField(
                choices=[('Ghaziabad', 'Ghaziabad'), ('New Delhi', 'New Delhi'), ('Gurugram', 'Gurugram'),
                         ('Chandigarh', 'Chandigarh'), ('Bangalore', 'Bangalore')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_state',
            field=models.CharField(
                choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Delhi', 'Delhi'), ('Haryana', 'Haryana'),
                         ('Punjab', 'Punjab'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_title',
            field=models.CharField(max_length=100),
        ),
    ]
