# Generated by Django 2.2 on 2019-04-10 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Property', '0003_auto_20190408_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_person_mail', models.EmailField(default='', max_length=254)),
                ('enquiry_description', models.TextField(max_length=200)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('enquiry_property',
                 models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Property.Properties')),
            ],
        ),
    ]
