# Generated by Django 2.2 on 2019-04-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_remove_profile_is_buyer'),
        ('Property', '0004_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='enquiry_property',
            new_name='property',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='enquiry_person_mail',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
