# Generated by Django 2.2 on 2019-04-12 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Property', '0005_auto_20190412_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
    ]
