# Generated by Django 2.2 on 2019-04-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Property', '0006_remove_enquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='properties',
            name='property_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
